# Generated by Django 5.2.4 on 2025-07-16 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscriptions',
            options={'permissions': [('basic', 'Basic Perm'), ('pro', 'Pro Perm'), ('advanced', 'Advanced Perm')]},
        ),
    ]
