# Generated by Django 5.2.4 on 2025-07-16 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('subscriptions', '0004_subscriptions_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptions',
            name='permissions',
            field=models.ManyToManyField(limit_choices_to={'codename_in': [('basic', 'Basic Perm'), ('pro', 'Pro Perm'), ('advanced', 'Advanced Perm')], 'content_type__app_label': 'subscriptions'}, to='auth.permission'),
        ),
    ]
